### ISSUE TITLE
Readme: Add info about creating the PAT

### ISSUE THREAD

**Issue by hormesiel** [rtvu/set-repository-description-action#1]
Hey, thanks for this action!

I'm currently trying to use it and I noticed that in the README there's no mention of how to create the `REPOSITORY_PAT` secret.

By looking at your code and the GitHub documentation I figured out that the required permission for the PAT is probably [Administration](https://docs.github.com/en/rest/authentication/permissions-required-for-fine-grained-personal-access-tokens?apiVersion=2022-11-28#repository-permissions-for-administration), but that'd be cool if it was mentioned directly in the README.

Thanks!

**Comment by rtvu** [comment]
Done
