### ISSUE TITLE
Tags: Add v1 sliding label

### ISSUE THREAD

**Issue by hormesiel** [rtvu/set-repository-description-action#2]
Thank you for this action which works very well and is easy to use 🙂

I just wanted to make a small suggestion: to add a "sliding" `v1` tag that would always be kept up-to-date with the latest `v1.x.x` release, [like GitHub does](https://github.com/actions/checkout/tags) [for their actions](https://github.com/hormesiel/todoist-create-task.gha/blob/main/.github/workflows/repo-description-update.yml#L9).

That would make it easier to stay up-to-date with your latest release. In practice :

```diff
- uses: rtvu/get-description-from-readme-action@v1.0.1
+ uses: rtvu/get-description-from-readme-action@v1
```

**Comment by rtvu** [comment]
Done
